### ISSUE TITLE
add topic tags in About section 

### ISSUE THREAD

**Issue by Beliavsky** [Cygnus000/Exponentes-de-Lyapunov#1]
I suggest adding the topics `lyapunov`, `lyapunov-exponent`, `dynamical-systems` in the About section at https://github.com/Cygnus000/Exponentes-de-Lyapunov

**Comment by bokol-ooch** [comment]
Thank you!

**Comment by Beliavsky** [comment]
I see that you added text in the About section, but my suggestion was to add topic tags so that your project shows up in searches. Please see https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics
